### ISSUE TITLE
[Bug]: imgproxy not working properly?

### ISSUE THREAD

**Issue by Jopo-JP** [tgdrive/teldrive#374]
### Describe the bug

Below is the `docker-compose.yml` file:

```yaml
services:
  teldrive:
    image: ghcr.io/tgdrive/teldrive
    restart: always
    container_name: teldrive
    volumes:
      - ./config.toml:/config.toml
      - ./session.db:/session.db
    ports:
      - 9080:8080
    networks:
      - internal
  db:
    image: ghcr.io/tgdrive/postgres
    container_name: postgres_db
    restart: always
    environment:
      - POSTGRES_USER=teldrive
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=postgres
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      - internal
  imgproxy:
    image: darthsim/imgproxy
    container_name: imgproxy
    environment:
      IMGPROXY_ALLOW_ORIGIN: "*"
      IMGPROXY_ENFORCE_WEBP: true
      IMGPROXY_MALLOC: "jemalloc"
    restart: always
    ports:
      - 9090:8080
    networks:
      - internal
networks:
  internal:
```

I updated the image resizer in the Teldrive GUI to `http://imgproxy:9090` and also tried `http://imgproxy:8080`, but there was no output in the `imgproxy` logs. 

I tested the network by entering the `imgproxy` container using `exec /bin/bash`, installed `ping`, and verified that I could reach Teldrive successfully. However, I am unable to test the connection from Teldrive since the container uses `scratch` with no available shell.

I assigned `imgproxy` a subdomain and visited it in the browser, where the page loaded as expected. I then updated the image resizer to `https://resizer.domain.td`, but received the following error:

```
imgproxy     | INFO    [2024-10-16T20:51:13Z] Started /insecure/w:360/plain/https%3A%2F%2Fresizer.domain.td%2Fapi%2Ffiles%2F019296ce-7fdc-7004-a941-2f8220ec4d99%2Fstream%2Ffolder.jpg%3Fhash%3D649bd3cd558e243af2aa50b85828f217  request_id=R5U3DMudkL5POKiC6OhFh method=GET client_ip=CLIENT_IP
imgproxy     | ERROR   [2024-10-16T20:51:43Z] Completed in 30.000314815s /insecure/w:360/plain/https%3A%2F%2Fresizer.domain.td%2Fapi%2Ffiles%2F019296ce-7fdc-7004-a941-2f8220ec4d99%2Fstream%2Ffolder.jpg%3Fhash%3D649bd3cd558e243af2aa50b85828f217  request_id=R5U3DMudkL5POKiC6OhFh method=GET status=504 client_ip=CLIENT_IP error="Can't download source image: The image request timed out: Get \"https://resizer.domain.td/api/files/019296ce-7fdc-7004-a941-2f8220ec4d99/stream/folder.jpg?hash=649bd3cd558e243af2aa50b85828f217\": dial tcp SERVER_IP:443: i/o timeout"
```

### Repoduction

1. Set up Teldrive and `imgproxy` within the same network using the `docker-compose.yml` configuration above.
2. Set the image resizer in the Teldrive GUI to point to `imgproxy`.

### Expected behavior

The images should be generated correctly and displayed in the web interface.

### Version

[1.5.3](https://github.com/tgdrive/teldrive/commits/1.5.3)

### Which Platform are you using?

Linux

### Additional context

For privacy reasons, I've redacted my client and server IP addresses.

The `imgproxy` container is reachable via the subdomain, and the network connectivity between containers has been confirmed from the `imgproxy` side.
