### ISSUE TITLE
cannot get imgproxy to work

### ISSUE THREAD

**Issue by abusivePenguin** [tgdrive/teldrive#478]
Cannot get imgproxy to work, teldrive is running locally and imgproxy on docker, ive tried networkmode=host for imgproxy but that doesnt seem to solve the issue. 
Im not that tech savvy so I think I am just doing something wrong. Any help is appreciated, thanks.

OS: Win 11
Teldrive Version: 1.6.13

Logs:
2025-05-25 12:36:33 INFO    [2025-05-25T04:36:33Z] Started //insecure/w:360/plain/http%3A%2F%2Flocalhost%3A8080%2Fapi%2Ffiles%2F01970153-e976-7035-886a-0c5b7f48d953%2FIMG_7327.JPG%3Fhash%3Df07c0d029611f9206df6c37007a5c1ec  request_id=a_0aH2lI3D_ncwRa5wMZ3 method=GET client_ip=172.18.0.1
2025-05-25 12:36:33 WARNING [2025-05-25T04:36:33Z] Completed in 284.066µs //insecure/w:360/plain/http%3A%2F%2Flocalhost%3A8080%2Fapi%2Ffiles%2F01970153-e976-7035-886a-0c5b7f48d953%2FIMG_7327.JPG%3Fhash%3Df07c0d029611f9206df6c37007a5c1ec  request_id=a_0aH2lI3D_ncwRa5wMZ3 method=GET status=404 client_ip=172.18.0.1 error="Invalid path: /insecure/w:360/plain/http%3A%2F%2Flocalhost%3A8080%2Fapi%2Ffiles%2F01970153-e976-7035-886a-0c5b7f48d953%2FIMG_7327.JPG%3Fhash%3Df07c0d029611f9206df6c37007a5c1ec"

**Comment by abusivePenguin** [comment]
using [ip]:[port] works.
localhost:[port] doesnt

**Comment by iwconfig** [comment]
- If you've defined `imgproxy` service along with `teldrive` within the same docker compose file, use the name of the `imgproxy` service as the domain instead of ip or localhost.
  
  ```yaml
  services:
    my-teldrive-service:
      image: ...
      # etc
    my-imgproxy-service:
      image: ...
      # etc
  ```
  
  and then `my-imgproxy-service:[port]`, because they share the same network.
  
- If you use separate docker compose files, either use the default network which `docker compose` defines automatically, or define a network manually and use that.
  - Using default network:

    ```yaml
    networks:
      the-project-name-of-my-imgproxy-service_default:
        external: true

    services:
      my-teldrive-service:
        image: ...
        networks:
          - the-project-name-of-my-imgproxy-service_default
        # etc
    ```

    and the project name of imgproxy is either
    - the name of the parent directory of your compose file.
      *i.e. /opt/stacks/**my_imgproxy**/compose.yml -> project name = **my_imgproxy***
    - or the name defined by the top-level directive "name", like this:

      ```yaml
      name: the-project-name-of-my-imgproxy-service
      services:
        my-imgproxy-service:
          image: ...
          # etc
      ```

  - Manually defined:
    - imgproxy compose file:

      ```yaml
      networks:
        whatever:
          external: true
  
      services:
        my-imgproxy-service:
          image: ...
          networks:
            - whatever
          # etc
      ```
    - teldrive compose file:

      ```yaml
      networks:
        whatever:
          external: true
  
      services:
        my-teldrive-service:
          image: ...
          networks:
            - whatever
          # etc
      ```
